apiVersion: apps/v1
kind: Deployment
metadata:
  name: testflask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testflask
  template:
    metadata:
      labels:
        app: testflask
    spec:
      containers:
      - name: testflask
        image: acrtestflask.azurecr.io/testflask:latest
        ports:
        - containerPort: 80   # Cambiado de 5000 a 80 para coincidir con la configuración de Flask
---
apiVersion: v1
kind: Service
metadata:
  name: testflask-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80           # Cambiado de 5000 a 80 para coincidir con el contenedor
  selector:
    app: testflask